version: "3.8"

services:
  backend:
    image: my-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - app-network

  frontend:
    image: my-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
