spring:
  application:
    name: flightsearchBT

amadeus:
  url: "https://test.api.amadeus.com/v1/security/oauth2/token"
  client_id: "dlWhv0lhA2qCNsMpABOv1NfPX8Ax7qtP"
  client_secret: "lrVVJ4HLNzHzfASU"

logging:
  level:
    root: INFO
    com.encora.flightsearchBT: DEBUG
  file:
    name: flightsearchBT.log

server:
  port: 9090